---
- name: EDA Hackathon Rulebook
  hosts: localhost
  sources:
    - name: listen for alerts
      ansible.eda.alertmanager:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: server down
      condition: event.alert.labels.job == "server" or event.alert.status == "firing"
      actions:
        - run_job_template:
          organization: Default
          name: "hk-shared-jt"
          job_args:
            extra_vars:
              job_template_name: "hk-shared-jt"
        - print_event:
            pretty: true