---
- name: EDA Hackathon Rulebook
  hosts: localhost
  sources:
    - name: Alertmanager
      ansible.eda.alertmanager:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: server down
      condition: event.payload.status == "firing"
      actions:
        - run_job_template:
            organization: Default
            name: "Demo Job Template"
            job_args:
              extra_vars:
                job_template_name: "Demo Job Template"
        - print_event:
            pretty: true