---
- name: Run a webhook listener service
  hosts: localhost
  sources:
    - name: webhook_listener
    - ansible.eda.webhook:
  rules:
    - name: Webhook event
      condition: event is not None
      action:
        debug:
          msg: event