---
- name: Test multiple actions and events
  hosts: all
  sources:
    - name: my test source
      ansible.eda.range:
        limit: 10
  rules:
    - name: rule with 2 actions/events
      condition:
        all: 
          - event.i == 3
          - event.i == 7
      actions:
        - debug:
            msg:
              - debug message 1
              - debug message 2