
---
- name: Ruleset 1 Test
  hosts: all
  sources:
    - ansible.eda.range:
        limit: 5
        delay: 4
  rules:
    - name: Say Hello
      condition: event.i == 1
      action:
        debug:
          msg: Event matched
    - name: Test 2nd rule
      condition: event.i == 2
      action:
        print_event:
    - name: Test 3rd rule
      condition: event.i == 3
      action:
        debug:
          msg: Event 3rd matched
- name: Ruleset 2 Test
  hosts: all
  sources:
    - ansible.eda.range:
        limit: 20 
        delay: 1
  rules:
    - name: Rule 1
      condition: event.i == 1
      action:
        debug:
          msg: Event matched
    - name: Rule 2
      condition: event.i == 2
      action:
        print_event:
    - name: Rule 3
      condition: event.i == 3
      action:
        debug:
          msg: Event 3rd matched
    - name: Rule 4
      condition: event.i == 4
      action:
        debug:
          msg: Event 4th matched